---

is_debug: true
ports:
  http_port: 3000 # If 0 then automatic port selection
  grpc_port: 4000 # If 0 then automatic port selection
  kafka_port: 9092
hosts:
  auth_host: mail-service-auth
  kafka_host: kafka
