services:
  postgres-db-analytics:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d